// * ACTIONS TYPES

// PAISES Y ACTIVIDADES
const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRY = "GET_COUNTRY";
const GET_COUNTRY_ID = "GET_COUNTRY_ID";
const GET_ACTIVITIES = "GET_ACTIVITIES";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";

// FILTRADO
const SET_CONTINENT_FILTER = "SET_CONTINENT_FILTER";
const SET_ACTIVITY_FILTER = "SET_ACTIVITY_FILTER";
const SET_ALPHABETICAL_ORDER = "SET_ALPHABETICAL_ORDER";
const SET_POPULATION_ORDER = "SET_POPULATION_ORDER";

export {
  GET_COUNTRIES,
  GET_COUNTRY,
  GET_COUNTRY_ID,
  GET_ACTIVITIES,
  SEARCH_BY_NAME,
  SET_CONTINENT_FILTER,
  SET_ACTIVITY_FILTER,
  SET_ALPHABETICAL_ORDER,
  SET_POPULATION_ORDER,
};
