// * ACTIONS TYPES

// RECETAS Y DIETAS
const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRY = "GET_COUNTRY";
const GET_ACTIVITIES = "GET_ACTIVITIES";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";
const GET_COUNTRY_ID = "GET_COUNTRY_ID";

// FILTRADO
const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
const ORDER_ALPH = "ORDER_ALPH";
const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";

// PAGINADO
// const CHANGE_PAGE = "CHANGE_PAGE";
// const SET_PAGE = "SET_PAGE";

export {
  GET_COUNTRIES,
  GET_COUNTRY,
  GET_COUNTRY_ID,
  GET_ACTIVITIES,
  SEARCH_BY_NAME,
  FILTER_BY_CONTINENT,
  FILTER_BY_ACTIVITY,
  ORDER_ALPH,
  ORDER_BY_POPULATION,
};
